### ISSUE TITLE
The getter 'pagesCount' was called on null.

### ISSUE THREAD

**Issue by Arcturus5404** [rbcprolabs/packages.flutter#102]
When switching back and forth to the PDF from another screen I always get this error when I pop back to the PDF screen:

```
The following NoSuchMethodError was thrown building PdfView(dirty, dependencies: [_EffectiveTickerMode], state: _PdfViewState#8cb19(ticker inactive)):
The getter 'pagesCount' was called on null.
Receiver: null
Tried calling: pagesCount
```

The relevant error-causing widget was: 
```
  PdfView lib/screens/project.dart:96:12
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      _PdfViewState._buildLoaded (package:native_pdf_view/src/native_pdf_view.dart:271:50)
#2      _PdfViewState.build (package:native_pdf_view/src/native_pdf_view.dart:307:18)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4619:28)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)
...
```

This is the line in PdfView:
        ` itemCount: widget.controller._document.pagesCount,`

**To Reproduce**
1. Open PDF
2. Navigate away
3. Go back with nagivator.popUntil page of PDF

**Expected behavior**
Not to break stuff

**Smartphone (please complete the following information):**
 - Device: Android

**Comment by Arcturus5404** [comment]
For context: It is a child in a stateful widget!

```
 Widget buildPdfView(Attachment attachment) {
    var pdfDocument = PdfDocument.openFile(attachment.pdf);
    var pdfController =
        PdfController(document: pdfDocument, initialPage: attachment.pdfPage != null ? attachment.pdfPage : 1);
    return PdfView(
      controller: pdfController,
      onPageChanged: (p) {
        attachment.pdfPage = p;
        DatabaseHelper.instance.update(attachment);
      },
      errorBuilder: (error) {
        print(error);
        return Text(t('error.pdfLoading'));
      },
    );
  }
```

**Comment by SergeShkurko** [comment]
are you dispose controller?

controller requires closing when the page is closed

and all controllers not recommended initialize in build method

```dart
class AttachmentPdfView extends StatefulWidget {
  const AttachmentPdfView({
    Key key,
    @required this.attachment,
  }) : super(key: key);

  final Attachment attachment;

  @override
  _AttachmentPdfViewState createState() => _AttachmentPdfViewState();
}

class _AttachmentPdfViewState extends State<AttachmentPdfView> {
  PdfController _pdfController;

  @override
  void initState() {
    final pdfDocument = PdfDocument.openFile(widget.attachment.pdf);
    _pdfController = PdfController(
      document: pdfDocument,
      initialPage:
          widget.attachment.pdfPage != null ? widget.attachment.pdfPage : 1,
    );
    super.initState();
  }

  @override
  void dispose() {
    _pdfController.dispose(); // <------------- !!!!!!!!!!!!!
    super.dispose();
  }

  int _onPageChanged(int page) {
    widget.attachment.pdfPage = page;
    DatabaseHelper.instance.update(widget.attachment);
  }

  @override
  Widget build(BuildContext context) => PdfView(
        controller: _pdfController,
        onPageChanged: _onPageChanged,
        errorBuilder: (error) {
          print(error);
          return Text(t('error.pdfLoading'));
        },
      );
}


// You new build method with wrapped PdfView
Widget buildPdfView(Attachment attachment) => AttachmentPdfView(
  attachment: attachment,
);
```
