### ISSUE TITLE
java.lang.OutOfMemoryError: Failed to allocate a 234270732 byte allocation with 12573184 free bytes and 176MB until OOM

### ISSUE THREAD

**Issue by 952055647** [rbcprolabs/packages.flutter#124]
/PDF_RENDER( 3965): OpenAssetDocument. Created file: /data/user/0/com.example.pdf/cache/f7b247adb5364eeab5c10264322aa5ea.pdf
D/PDF_RENDER( 3965): OpenFileDocument. File: /data/user/0/com.example.pdf/cache/f7b247adb5364eeab5c10264322aa5ea.pdf
I/art     ( 3965): Starting a blocking GC Alloc
I/art     ( 3965): Starting a blocking GC Alloc
I/art     ( 3965): Alloc sticky concurrent mark sweep GC freed 25473(1447KB) AllocSpace objects, 3(60KB) LOS objects, 45% free, 15MB/28MB, paused 270us total 18.366ms
I/art     ( 3965): Starting a blocking GC Alloc
I/art     ( 3965): Alloc partial concurrent mark sweep GC freed 89(3KB) AllocSpace objects, 0(0B) LOS objects, 43% free, 15MB/27MB, paused 226us total 16.424ms
I/art     ( 3965): Starting a blocking GC Alloc
I/art     ( 3965): Alloc concurrent mark sweep GC freed 12(12KB) AllocSpace objects, 0(0B) LOS objects, 43% free, 15MB/27MB, paused 222us total 18.630ms
I/art     ( 3965): Forcing collection of SoftReferences for 223MB allocation
I/art     ( 3965): Starting a blocking GC Alloc
I/art     ( 3965): Alloc concurrent mark sweep GC freed 11(352B) AllocSpace objects, 0(0B) LOS objects, 44% free, 15MB/27MB, paused 183us total 15.377ms
W/art     ( 3965): Throwing OutOfMemoryError "Failed to allocate a 234270732 byte allocation with 12574960 free bytes and 176MB until OOM"
I/art     ( 3965): Starting a blocking GC Alloc
I/art     ( 3965): Starting a blocking GC Alloc
I/art     ( 3965): Starting a blocking GC Alloc
I/art     ( 3965): Alloc partial concurrent mark sweep GC freed 12(480B) AllocSpace objects, 0(0B) LOS objects, 44% free, 15MB/27MB, paused 266us total 7.434ms
I/art     ( 3965): Starting a blocking GC Alloc
I/art     ( 3965): Alloc concurrent mark sweep GC freed 3(96B) AllocSpace objects, 0(0B) LOS objects, 43% free, 15MB/27MB, paused 195us total 14.947ms
I/art     ( 3965): Forcing collection of SoftReferences for 223MB allocation
I/art     ( 3965): Starting a blocking GC Alloc
I/art     ( 3965): Alloc concurrent mark sweep GC freed 3(96B) AllocSpace objects, 0(0B) LOS objects, 44% free, 15MB/27MB, paused 202us total 17.525ms
W/art     ( 3965): Throwing OutOfMemoryError "Failed to allocate a 234270732 byte allocation with 12573184 free bytes and 176MB until OOM"
E/AndroidRuntime( 3965): FATAL EXCEPTION: Thread-930
E/AndroidRuntime( 3965): Process: com.example.pdf, PID: 3965
E/AndroidRuntime( 3965): java.lang.OutOfMemoryError: Failed to allocate a 234270732 byte allocation with 12573184 free bytes and 176MB until OOM
E/AndroidRuntime( 3965): 	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
E/AndroidRuntime( 3965): 	at android.graphics.Bitmap.nativeCreate(Native Method)
E/AndroidRuntime( 3965): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:859)
E/AndroidRuntime( 3965): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:829)
E/AndroidRuntime( 3965): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:796)
E/AndroidRuntime( 3965): 	at io.scer.pdf.renderer.document.Page.render(Page.kt:35)
E/AndroidRuntime( 3965): 	at io.scer.pdf.renderer.NativePDFRendererPlugin$renderHandler$1.run(NativePDFRendererPlugin.kt:169)
E/AndroidRuntime( 3965): 	at java.lang.Thread.run(Thread.java:833)
I/Process ( 3965): Sending signal. PID: 3965 SIG: 9

**Comment by 952055647** [comment]
[b.pdf](https://github.com/rbcprolabs/packages.flutter/files/5369124/b.pdf)
打开此pdf报错
