### ISSUE TITLE
Corrupted file crash the whole application onDocumentError is not working !

### ISSUE THREAD

**Issue by larrylinus** [rbcprolabs/packages.flutter#128]
E/AndroidRuntime( 6986): FATAL EXCEPTION: Thread-19
E/AndroidRuntime( 6986): Process: studymaterials.studymaterials, PID: 6986
E/AndroidRuntime( 6986): java.io.IOException: file not in PDF format or corrupted
E/AndroidRuntime( 6986): 	at android.graphics.pdf.PdfRenderer.nativeCreate(Native Method)
E/AndroidRuntime( 6986): 	at android.graphics.pdf.PdfRenderer.<init>(PdfRenderer.java:167)
E/AndroidRuntime( 6986): 	at io.scer.pdf.renderer.NativePDFRendererPlugin.openFileDocument(NativePDFRendererPlugin.kt:202)
E/AndroidRuntime( 6986): 	at io.scer.pdf.renderer.NativePDFRendererPlugin.access$openFileDocument(NativePDFRendererPlugin.kt:30)
E/AndroidRuntime( 6986): 	at io.scer.pdf.renderer.NativePDFRendererPlugin$openDocumentFileHandler$1.run(NativePDFRendererPlugin.kt:70)
E/AndroidRuntime( 6986): 	at java.lang.Thread.run(Thread.java:764)
I/Process ( 6986): Sending signal. PID: 6986 SIG: 9

**Comment by lijy91** [comment]
try catch cannot catch errors that occur in Thread.

Before
```kotlin
private fun openDocumentFileHandler(call: MethodCall, result: Result) {
    try {
        val path = call.arguments<String>()!!
        Thread {
            val documentRenderer = openFileDocument(File(path))
            result.success(documents.register(documentRenderer).infoMap)
        }.start()
    } catch (e: NullPointerException) {
        result.error("PDF_RENDER", "Need call arguments: path", null)
    } catch (e: FileNotFoundException) {
        result.error("PDF_RENDER", "File not found", null)
    } catch (e: IOException) {
        result.error("PDF_RENDER", "Can't open file", null)
    } catch (e: CreateRendererException) {
        result.error("PDF_RENDER", "Can't create PDF renderer", null)
    } catch (e: Exception) {
        result.error("PDF_RENDER", "Unknown error", null)
    }
}
```

After

```kotlin
private fun openDocumentFileHandler(call: MethodCall, result: Result) {
    Thread {
        try {
            val path = call.arguments<String>()!!
            val documentRenderer = openFileDocument(File(path))
            result.success(documents.register(documentRenderer).infoMap)
        } catch (e: NullPointerException) {
            result.error("PDF_RENDER", "Need call arguments: path", null)
        } catch (e: FileNotFoundException) {
            result.error("PDF_RENDER", "File not found", null)
        } catch (e: IOException) {
            result.error("PDF_RENDER", "Can't open file", null)
        } catch (e: CreateRendererException) {
            result.error("PDF_RENDER", "Can't create PDF renderer", null)
        } catch (e: Exception) {
            result.error("PDF_RENDER", "Unknown error", null)
        }
    }.start()
}
```
