### ISSUE TITLE
Open PDF pages not works flutter web.

### ISSUE THREAD

**Issue by Tapasm1212** [rbcprolabs/packages.flutter#204]
I am working on the flutter web project and try out the pdf open functionality. I am using this code for opening the pdf 

`  
    void _createWidget(PlatformFile file) async {
    //Uint8List
    PdfDocument docFromAsset = await PdfDocument.openData(file.bytes);
    int pageCount = docFromAsset.pagesCount;

    for (int i = 0; i < pageCount; i++) {
      PdfPage page = await docFromAsset.getPage(i + 1);
      PdfPageImage pageImage = await page.render(width: page.width, height: page.height);

    new pw.Container(height: 840, child: pw.Image(pw.MemoryImage(
              pageImage.bytes), fit: pw.BoxFit.fill));

    }
  }`

but it does not work to open the pdf and getting below error

TypeError: Cannot read property 'layout' of null
    at multi_page.MultiPage.new.generate (http://localhost:54581/packages/pdf/src/widgets/table.dart.lib.js:16652:15)
    at document$0.Document.new.addPage (http://localhost:54581/packages/pdf/src/widgets/table.dart.lib.js:18301:12)
    at body$4._BodyState.new.createPdf (http://localhost:54581/packages/bms/screens/NewClaim/components/claim_form.dart.lib.js:26735:66)
    at createPdf.next (<anonymous>)
    at http://localhost:54581/dart_sdk.js:39032:33
    at _RootZone.runUnary (http://localhost:54581/dart_sdk.js:38889:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:54581/dart_sdk.js:33875:29)
    at handleValueCallback (http://localhost:54581/dart_sdk.js:34435:49)
    at Function._propagateToListeners (http://localhost:54581/dart_sdk.js:34473:17)
    at _Future.new.[_completeWithValue] (http://localhost:54581/dart_sdk.js:34315:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:54581/dart_sdk.js:34338:35)
    at Object._microtaskLoop (http://localhost:54581/dart_sdk.js:39176:13)
    at _startMicrotaskLoop (http://localhost:54581/dart_sdk.js:39182:13)
    at http://localhost:54581/dart_sdk.js:34689:9
Error: MissingPluginException(No implementation found for method open.document.data on channel io.scer.pdf.renderer)
    at Object.throw_ [as throw] (http://localhost:54581/dart_sdk.js:5334:11)
    at MethodChannel._invokeMethod (http://localhost:54581/packages/flutter/src/services/system_channels.dart.lib.js:954:21)
    at _invokeMethod.next (<anonymous>)
    at http://localhost:54581/dart_sdk.js:39032:33
    at _RootZone.runUnary (http://localhost:54581/dart_sdk.js:38889:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:54581/dart_sdk.js:33875:29)
    at handleValueCallback (http://localhost:54581/dart_sdk.js:34435:49)
    at Function._propagateToListeners (http://localhost:54581/dart_sdk.js:34473:17)
    at _Future.new.[_completeWithValue] (http://localhost:54581/dart_sdk.js:34315:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:54581/dart_sdk.js:34338:35)
    at Object._microtaskLoop (http://localhost:54581/dart_sdk.js:39176:13)
    at _startMicrotaskLoop (http://localhost:54581/dart_sdk.js:39182:13)
    at http://localhost:54581/dart_sdk.js:34689:9

I have added the script in the index.html file before importing main.dart.js. but it's not working giving this error everytime when want to get the pages from a pdf. 

Can you please suggest how can we resolve this issue? Thanks in advance.

**Comment by youssef-fk** [comment]
Facing this issue also.

**Comment by SergeShkurko** [comment]
I can't repeat with `native_pdf_renderer: ^3.1.0` and `flutter: `2.5.2`
try run example
```
git clone https://github.com/rbcprolabs/packages.flutter.git
cd packages.flutter/packages/native_pdf_renderer/example
flutter run -d chrome
```

and attach here `flutter doctor` result
