### ISSUE TITLE
Native_pdf_renderer crashes a lot

### ISSUE THREAD

**Issue by lazylazyllama** [rbcprolabs/packages.flutter#53]
**Describe the bug**
```
E/AndroidRuntime(14575): FATAL EXCEPTION: Thread-16
E/AndroidRuntime(14575): Process: de.gebatzens.sia, PID: 14575
E/AndroidRuntime(14575): io.scer.pdf.renderer.resources.RepositoryItemNotFoundException: 63c623e9-64e1-4c23-8b18-a28b18d8f27c
E/AndroidRuntime(14575): 	at io.scer.pdf.renderer.resources.Repository.get(Repository.kt:12)
E/AndroidRuntime(14575): 	at io.scer.pdf.renderer.NativePDFRendererPlugin$openPageHandler$1.run(NativePDFRendererPlugin.kt:129)
E/AndroidRuntime(14575): 	at java.lang.Thread.run(Thread.java:919)
I/Process (14575): Sending signal. PID: 14575 SIG: 9
```

**To Reproduce**
When I open a pdf file with the native_pdf_renderer sometimes it crashes. 

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 9T Pro
 - OS: Android 10

**Comment by SergeShkurko** [comment]
@lazylazyllama can you show the code leading to the problem?

**Comment by lazylazyllama** [comment]
Okay I will do that when I find time next week
